---

# Install Chronograf
- name: Include the playbook that handles installation of Chronograf package
  include: "{{ ansible_os_family }}_install.yml"
  tags: tickstack-chronograf

# Configure Chronograf
- name: Include the playbook that handles configuration of Chronograf service
  include: "{{ ansible_os_family }}_configure.yml"
  tags: tickstack-chronograf
