#!/bin/bash
###############################################################################
#
# {{ ansible_managed }}
#
# DO NOT EDIT THIS FILE AS CHANGES WILL BE OVERWRITTEN
#
###############################################################################

set -e

# Purge old dir first
[[ -d /tmp/jenkins-duply ]] && rm -rf /tmp/jenkins-duply
mkdir /tmp/jenkins-duply

tar -czf /tmp/jenkins-duply/jenkins.tar /var/lib/jenkins
