#!/bin/bash
###############################################################################
#
# {{ ansible_managed }}
#
# DO NOT EDIT THIS FILE AS CHANGES WILL BE OVERWRITTEN
#
###############################################################################

set -e

rm -rf /tmp/jenkins-duply
