---

- name: chronograf restart
  service:
    name: chronograf
    state: restarted
  tags: tickstack-chronograf

- name: chronograf stop
  service:
    name: chronograf
    state: stopped
  tags: tickstack-chronograf

- name: chronograf start
  service:
    name: chronograf
    state: started
    enabled: yes
  tags: tickstack-chronograf

- name: systemd reload
  shell: |
    # Reload daemon after changing service configuration file
    systemctl daemon-reload
  tags: tickstack-chronograf

- name: restart nginx
  service:
    name: nginx
    state: restarted
