---

- name: "Add repository key"
  apt_key:
    url: "https://pkg.jenkins.io/debian/jenkins-ci.org.key"
  environment: "{{proxy_env}}"

- name: "Add repository"
  apt_repository:
    repo: deb http://pkg.jenkins.io/debian-stable binary/

- name: "Install packages"
  apt:
    name: jenkins
    state: latest
    update_cache: yes
  environment: "{{proxy_env}}"
